
#include "render_settings.hpp"

/* Default values */
int AA = 2;

bool AA_OPTIMIZE = false;
double AA_OPTIMIZE_AVGDIFFACCEPTED = 2.0;
double AA_OPTIMIZE_MAXDIFFACCEPTED = 200.0;

int NUM_SCREENS = 16;
int NUM_THREADS = 4;

bool RUN_REFLECTION = true;
bool RUN_REFLECTION_DIFFUSE = true;
bool RUN_REFLECTION_SPECULAR = true;
bool RUN_LIGHT = true;
bool RUN_LIGHT_ATMOSPHEREREF = true;

int STACK_DEPTH_ATMOSPHERE = 5;
int STACK_DEPTH_DIFFUSE = 5;
int STACK_DEPTH_SPECULAR = 5;

double MAX_STACK_DEPTH = 100.0;

int STACK_DEPTH_ATMOSPHERE_ADD = MAX_STACK_DEPTH / STACK_DEPTH_ATMOSPHERE;
int STACK_DEPTH_DIFFUSE_ADD = MAX_STACK_DEPTH / STACK_DEPTH_DIFFUSE;
int STACK_DEPTH_SPECULAR_ADD = MAX_STACK_DEPTH / STACK_DEPTH_SPECULAR;

int MAX_ATMOSPHERE_ITERATIONS = 2;



void load_settings() 
{
    // load from file
}